services:
  vincela-web:
    build: .
    image: vincela-site:latest
    restart: unless-stopped
    networks:
      proxy-net:
        aliases:
          - vincela-web

networks:
  proxy-net:
    external: true
