server {
    listen 80;
    server_name _;
    server_tokens off;

    root /usr/share/nginx/html;
    index index.html;

    location = /experiencer {
        return 301 https://experiencer.vincela.com/$is_args$args;
    }

    location ~ ^/experiencer(/.*)?$ {
        return 301 https://experiencer.vincela.com$1$is_args$args;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
